### ISSUE TITLE
[MDSR] Make all the visits general encounters.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#12]
### App

- [x] App Changes
     - [x] Change Encounter type
     - [x] Change formMappings
     - [x] Change enrolment form to registration form
     - [x] Rules Changes
         - Task in FEG & FE rules- by DB query approach
            - [x] Replace programEncounter to encounter
            - [x] replace valueInEnrolment to Value in registration
            - [x] update to take value from registration for the value in entire enrolment
         - Form level rules
            - [x] Visit Scheduling
            - [x] Decision
            - [x] Validation

#### Reports
- [x] Update view in reports
- [x] Update jasper reports variables

- Remove the program from report
  - Task
    - [x] Regenerate views 
    - [x] Update view names
    - [x] Update joins & selects names from reports

**Comment by sachsk** [comment]
@garimadosar5 
apk link https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-1a38-2020-11-02-16-35-43.apk
user id for uat testing:
id: commonuser@mdsrcg-uat
password: password
