### ISSUE TITLE
[MDSR-CG] Form6 and form 1 changes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#14]
https://docs.google.com/document/d/1ER9b9kdYWVpVXRzWB1AVLNZ8WWDgiika/edit?dls=true

- In all the forms - RCH Number / MCTS No. It should be written in single format RCH No. / MCTS No. - **_DONE_**

- **Form -1** 
**On the second Page-**
**Ques - What is the Native address?** --**Done**
Options -
1. Same as Current
2. Different from current but within Chhattisgarh
3. Outside Chhattisgarh

**Native Address - (If 2nd option is selected)**  --**Done**
1. District - Single select (mandatory)
2. Block - Text (mandatory)
3. Address - Text (non-mandatory)

**Native Address - (If 3rd option is selected)** --**Done**
1. State - Text field (mandatory)
2. District - Text field (mandatory)
3. Block - Text field (mandatory)
4. Address - Text field (non-mandatory)

- ** Report Change for Native Address -** 
Show this native address in the line lists - _

- [x] Line list of CBMD review
- [x] MDSR common linelist
- [x] Places visited prior to facility where died

- Form 6 - 
Add new question for Native address and  Auto fill Native address from form 1.

**Comment by arjunk** [comment]
@sachsk @garimadosar5 is this card still to be done?

**Comment by garimadosar5** [comment]
QA Notes - 
- In all the line list address is not showing properly. - **_DONE_**
**Column Name**
District
Block
UPHC/PHC/CHC/UCHC
SHC/SSK
Village

**Comment by garimadosar5** [comment]
QA Notes - 2

>>In form 4, FEG cause of death ( towards the end) is not working. please check.
1. In direct cause, 
- if any option is selected, it is giving error "there should be only one value specified".
- If No option is selected, it is giving error, "No value specified".
2. In Indirect causes, No values are shown, and form is not going forward.
3. Same for other two causes.
