### ISSUE TITLE
[MDSR][CG] Changes in form 4,5,6

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#21]
Ref doc - https://docs.google.com/spreadsheets/d/1Z4PZ7sO9PVQy4q3_fN3NPXQKqbbz1H7J/edit?usp=drive_web&ouid=115444501370582801094&rtpof=true

**Comment by sachsk** [comment]
In form 5 group X
Ques."Referral Time of onset of complication or onset of labor from Facility 1"
this ques. is time type so we cant compare time with date time.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- "Date and time of admission to ICU" and "Date and time of discharge from ICU" (form 4). these should not be after date and time of death.
and discharge date time cannot be before admission datetime.
- Obstetric History part is not prefilled in form 6. It was given by Dr rashid before.
- Investigation team is not prefilled in form 6 as given before.

**Comment by sachsk** [comment]
In form 4 investigation team details are not available
