### ISSUE TITLE
[MDSR-CG] Create Address hierarchy

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#3]
![IMG20201026094052.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/97473011-bbd2-419f-b9e2-47a3d1f5e56e)
Ref Doc (UCHC) - https://docs.google.com/spreadsheets/d/10-cA1KHjhjfsqB2zqcrcB6BSBpLM2oHH/edit#gid=1944363823\
Ref Doc (UPHC and SSK) - https://docs.google.com/spreadsheets/d/10-cA1KHjhjfsqB2zqcrcB6BSBpLM2oHH/edit#gid=1726275471
Ref Doc - (Rural Hierarchy) - https://docs.google.com/spreadsheets/d/10-cA1KHjhjfsqB2zqcrcB6BSBpLM2oHH/edit#gid=1404004192

Facilities - 
DH - https://docs.google.com/spreadsheets/d/10-cA1KHjhjfsqB2zqcrcB6BSBpLM2oHH/edit#gid=1954967389
Medical colleges - https://docs.google.com/spreadsheets/d/1wknvSKO837Z8FuxJ7TX_FBVIb_BDGM4h/edit#gid=956348320
Sub district hospital - https://docs.google.com/spreadsheets/d/1wknvSKO837Z8FuxJ7TX_FBVIb_BDGM4h/edit#gid=273714402
FRU - https://docs.google.com/spreadsheets/d/1wknvSKO837Z8FuxJ7TX_FBVIb_BDGM4h/edit#gid=566895059

**Comment by sachsk** [comment]
user for testing
user id:commonuser@mdsrcg
password: password


facility user:
bilaspur_college@mdsrcg
