### ISSUE TITLE
[MDSR-CG] Deploy rules for MDSR-CG org.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#5]
### Tech Task

- [x] Migrate forms rule
     - [x] community based verbal
     - [x] mdsr notification
     - [x] case summary
    - [x] mdsr registration form(facility based)
- [x] summary rules etc.
- [x] visit schedule

**Comment by garimadosar5** [comment]
QA Notes-  
- Form 4 
**Admission Summary** - Admission -> Delivery interval and Admission -> Death Interval are not calculated.
- Form 4is not going forward after cause of death. - **DONE**
- Cause of death - only one cause can be selected for direct or indirect cause. (this is done for Unicef-moha. Ask Nupoor) - **NOT DONE**
- Form 5
**For investigation of maternal deaths** - Date of investigation. date validation is not working. showing "Date/ time of investigation cannot be before date/time of death". and form is not going forward. - **NOT DONE**

**Comment by sachsk** [comment]
Please sync the app.
