### ISSUE TITLE
[MDSR-CG][Report] Create all the reports for MDSR-CG same as Moha

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#7]
### Tech Task 

- [x] Export reports from jasper make required changes and upload it in MDSR-CG directory 
- [x] Update the reports

**Comment by sachsk** [comment]
On hold due to making changes in app

**Comment by garimadosar5** [comment]
QA Notes - 
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FMDSR_CG%2FReports%2FAggregates&reportUnit=%2FMDSR_CG%2FReports%2FAggregates%2FPlaces_visited_prior_to_facility&standAlone=true

Here make report till 7 as we have done 7 places.
make that change in Moha also.
