### ISSUE TITLE
[MDSR] Form 5 location hierarchy.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/MDSR-CG#8]
https://drive.google.com/drive/folders/1w2t63ZrFAccQWNC2J0QPC2pk7ICYCAWv

Form 5
FEG - For investigation of maternal deaths
FE - State, district etc.etc..... Make it
Rural -
District
Block
PHC
Subcenter

Urban-
District
City/Town
UPHC/UCHC

**Comment by garimadosar5** [comment]
QA Notes - 
- In registration form just show district and block.
- Form 5. PHC is not there
![1602306437344.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/41729853-bec0-4c2a-827a-0e2127ea04a0)


- MDSR -CG
Case - Suman Saini
Check in form 5, if images are synce and can be used in reports

**Comment by sachsk** [comment]
we can use images in reports.

**Comment by garimadosar5** [comment]
QA Notes - 
- Subcenters are not available in the address and it is throwing error.
![Screenshot_2020-10-12-11-58-33-34.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/e5f790a0-ff0e-44fe-a610-090ccd5d4600)

**Comment by sachsk** [comment]
@garimadosar5 use this apk
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-e0ca-2020-10-14-15-10-56.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- For subcenter, it is showing he complete list of block
